{
 "title": "Top 5 Activities",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top Countries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total[1m])) by (geo))",
     "legendFormat": "{{ geo }}"
    }
   ]
  },
  {
   "title": "URLMaps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total[1m])) by (urlmap))",
     "legendFormat": "{{ urlmap }}"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total[1m])) by (method))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Blocked Methods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(curiemetric_session_details_total{blocked=\"true\"} [1m])) by (method) )",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "URLs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total[1m])) by (path))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Blocked URLs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total{blocked=\"true\"} [1m])) by (path))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Blocking WAF IDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(curiemetric_session_details_total{blocked=\"true\"} [1m])) by (wafid) )",
     "legendFormat": "{{ wafid }}"
    }
   ]
  },
  {
   "title": "Blocking ACL IDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(curiemetric_session_details_total{blocked=\"true\"} [1m])) by (aclid) )",
     "legendFormat": "{{ aclid }}"
    }
   ]
  },
  {
   "title": "ASN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " topk(5, rate(curiemetric_session_details_total[1m] )) by (asn)",
     "legendFormat": "{{ asn }}"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " topk(5, rate(curiemetric_session_tags_total[1m] )) by (tag)",
     "legendFormat": "{{ tag }}"
    }
   ]
  }
 ]
}